### ISSUE TITLE
Error importing with vite

### ISSUE THREAD

**Issue by Nedi11** [lmsqueezy/lemonsqueezy.js#21]
Failed to resolve entry for package "@lemonsqueezy/lemonsqueezy.js". The package may have incorrect main/module/exports specified in its package.json.

I get this when using remix with vite.

**Comment by JohnCido** [comment]
Same issue with SolidStart+Vite, any possible solution?

**Comment by JohnCido** [comment]
In the `package.json`, the following `module` entry is included:
```json
...
"module": "dist/index.mjs",
...
```
But the `index.mjs` file is **not** present in the `dist` folder.
Once I change the `dist/index.mjs` to `dist/index.js` in `node_modules`, everything works fine. The API call works correctly too.
This should be considered as critical bug since it will effect all Vite-based projects.

**Comment by gilbitron** [comment]
This is fixed in [v1.2.2](https://github.com/lmsqueezy/lemonsqueezy.js/releases/tag/v1.2.2)
