### ISSUE TITLE
Add clearer docs for set up

### ISSUE THREAD

**Issue by elie222** [lmsqueezy/lemonsqueezy.js#59]
Is this the expected usage in v2? Would be nice to show a simple example in the README with the new setup function.

```ts
import { env } from "@/env.mjs";
import { lemonSqueezySetup, updateSubscriptionItem } from "@lemonsqueezy/lemonsqueezy.js";

function setUpLemon() {
  if (!env.LEMON_SQUEEZY_API_KEY) return;
  lemonSqueezySetup({apiKey: env.LEMON_SQUEEZY_API_KEY });
}

export async function updateSubscriptionItemQuantity(options: {
  id: number;
  quantity: number;
}) {
  setUpLemon();
  return updateSubscriptionItem(options.id, options.quantity);
}
```

**Comment by keyding** [comment]
Hi, @elie222.

Just call the `lemonSqueezySetup` function once before using any of the functions.

```ts
import { env } from "@/env.mjs";
import { lemonSqueezySetup, updateSubscriptionItem } from "@lemonsqueezy/lemonsqueezy.js";

lemonSqueezySetup({apiKey: env.LEMON_SQUEEZY_API_KEY });

export async function updateSubscriptionItemQuantity(options: {
  id: number;
  quantity: number;
}) {
  return updateSubscriptionItem(options.id, options.quantity);
}
```

I hope this helps.

**Comment by keyding** [comment]
Also, the `updateSubscriptionItem` function will have a break change in the future because the official API added [two new parameters](https://docs.lemonsqueezy.com/api/subscription-items#update-a-subscription-item). I have to admit that this was a design error on my part. Please stay tuned for the next new version.
